import { teamsMatch } from "@/lib/squads/team-names";

const COUNTRY_CODES: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  angola: "AO",
  argentina: "AR",
  australia: "AU",
  austria: "AT",
  belgium: "BE",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  brazil: "BR",
  bulgaria: "BG",
  cameroon: "CM",
  canada: "CA",
  chile: "CL",
  china: "CN",
  "china pr": "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  ecuador: "EC",
  egypt: "EG",
  england: "GB-ENG",
  france: "FR",
  germany: "DE",
  "west germany": "DE",
  "soviet union": "RU",
  "fr yugoslavia": "RS",
  ghana: "GH",
  greece: "GR",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  "republic of ireland": "IE",
  israel: "IL",
  italy: "IT",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  "ivory coast": "CI",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  "korea republic": "KR",
  "korea rep": "KR",
  "south korea": "KR",
  "republic of korea": "KR",
  "korea dpr": "KP",
  "north korea": "KP",
  kuwait: "KW",
  mexico: "MX",
  morocco: "MA",
  netherlands: "NL",
  "new zealand": "NZ",
  nigeria: "NG",
  "northern ireland": "GB-NIR",
  norway: "NO",
  panama: "PA",
  paraguay: "PY",
  peru: "PE",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  "saudi arabia": "SA",
  scotland: "GB-SCT",
  senegal: "SN",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  togo: "TG",
  tunisia: "TN",
  turkey: "TR",
  ukraine: "UA",
  "united arab emirates": "AE",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  "u.s.": "US",
  uruguay: "UY",
  venezuela: "VE",
  wales: "GB-WLS",
  yugoslavia: "RS",
  zaire: "CD",
  "dr congo": "CD",
  "democratic republic of the congo": "CD",
  "cape verde": "CV",
  "cabo verde": "CV",
  curacao: "CW",
  haiti: "HT",
  uzbekistan: "UZ",
  "ir iran": "IR",
  "trinidad and tobago": "TT",
  "trinidad & tobago": "TT",
  "china pr.": "CN",
  "bosnia-herzegovina": "BA",
  czechoslovakia: "CZ",
  "east germany": "DE",
  "german democratic republic": "DE",
  lebanon: "LB",
  libya: "LY",
  mali: "ML",
  nepal: "NP",
  nicaragua: "NI",
  "new caledonia": "NC",
  "north macedonia": "MK",
  macedonia: "MK",
  montenegro: "ME",
  myanmar: "MM",
  "burma": "MM",
  oman: "OM",
  palestine: "PS",
  "syria": "SY",
  thailand: "TH",
  uae: "AE",
  "u.a.e.": "AE",
  vietnam: "VN",
  "viet nam": "VN",
  zambia: "ZM",
  zimbabwe: "ZW",
  anguilla: "AI",
  armenia: "AM",
  azerbaijan: "AZ",
  belarus: "BY",
  benin: "BJ",
  botswana: "BW",
  "burkina faso": "BF",
  burundi: "BI",
  cambodia: "KH",
  "central african republic": "CF",
  chad: "TD",
  comoros: "KM",
  cyprus: "CY",
  estonia: "EE",
  ethiopia: "ET",
  finland: "FI",
  gabon: "GA",
  gambia: "GM",
  georgia: "GE",
  grenada: "GD",
  guatemala: "GT",
  guinea: "GN",
  "guinea-bissau": "GW",
  guyana: "GY",
  "hong kong": "HK",
  indonesia: "ID",
  kazakhstan: "KZ",
  kenya: "KE",
  kosovo: "XK",
  kyrgyzstan: "KG",
  latvia: "LV",
  lesotho: "LS",
  liberia: "LR",
  lithuania: "LT",
  luxembourg: "LU",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mauritania: "MR",
  mauritius: "MU",
  moldova: "MD",
  mongolia: "MN",
  mozambique: "MZ",
  namibia: "NA",
  niger: "NE",
  "papua new guinea": "PG",
  "puerto rico": "PR",
  rwanda: "RW",
  "san marino": "SM",
  "sierra leone": "SL",
  singapore: "SG",
  somalia: "SO",
  sudan: "SD",
  "south sudan": "SS",
  suriname: "SR",
  tanzania: "TZ",
  "timor-leste": "TL",
  "east timor": "TL",
  uganda: "UG",
  yemen: "YE"
};

function normalizeKey(value: string) {
  return value
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .trim();
}

export function resolveCountryCode(teamOrCountry: string | null | undefined) {
  if (!teamOrCountry) return null;

  const normalized = normalizeKey(teamOrCountry);
  if (COUNTRY_CODES[normalized]) {
    return COUNTRY_CODES[normalized];
  }

  const withoutSuffix = normalized.replace(/\s+(fc|sc|cf)$/u, "");
  if (COUNTRY_CODES[withoutSuffix]) {
    return COUNTRY_CODES[withoutSuffix];
  }

  for (const [name, code] of Object.entries(COUNTRY_CODES)) {
    if (teamsMatch(teamOrCountry, name)) return code;
  }

  return null;
}

export type FlagDisplaySize = "xs" | "sm" | "md";

/** flagcdn.com only serves fixed WxH assets (not arbitrary w32, w48, etc.). */
const FLAGCDN_DIMENSIONS: Record<FlagDisplaySize, string> = {
  xs: "32x24",
  sm: "40x30",
  md: "48x36"
};

export function flagImageUrl(code: string, displaySize: FlagDisplaySize = "sm") {
  const normalized = code.toLowerCase().replace(/_/g, "-");
  const dimensions = FLAGCDN_DIMENSIONS[displaySize];
  return `https://flagcdn.com/${dimensions}/${normalized}.png`;
}
